CC0=cc0
FLAGS=-x

TESTS=sortedlist-test.c0
LIB=listlib.c0

all: 1 2 3 4 5

1:
	$(info Testing Implementation 1...)
	-$(CC0) $(FLAGS) $(LIB) sortedlist-bad1.c0 $(TESTS)
	@echo "";

2:
	$(info Testing Implementation 2...)
	-$(CC0) $(FLAGS) $(LIB) sortedlist-bad2.c0 $(TESTS)
	@echo "";

3:
	$(info Testing Implementation 3...)
	-$(CC0) $(FLAGS) $(LIB) sortedlist-bad3.c0 $(TESTS)
	@echo "";

4:
	$(info Testing Implementation 4...)
	-$(CC0) $(FLAGS) $(LIB) sortedlist-bad4.c0 $(TESTS)
	@echo "";

5:
	$(info Testing Implementation 5...)
	-$(CC0) $(FLAGS) $(LIB) sortedlist-bad5.c0 $(TESTS)
	@echo "";
